Repository Zeeve-App/larch, pull requests merged in 2023-04, with the labels that each got.

#57 add user operations API's, data model and data management functions
  packages/backend/migrations/0.initial.js
  packages/backend/src/api/larch/index.ts
  packages/backend/src/api/larch/network/controllers.ts
  packages/backend/src/api/larch/network/validations.ts
  packages/backend/src/api/larch/template/controllers.ts
  packages/backend/src/api/larch/template/validations.ts
  packages/backend/src/api/larch/user_operation/controllers.ts
  packages/backend/src/api/larch/user_operation/routes.ts
  packages/backend/src/modules/models/user_operation.ts
  packages/backend/src/modules/user_operation.ts
Labels: feature

#61 add pagination support for listing apis
  packages/backend/src/api/larch/template/controllers.ts
  packages/backend/src/api/larch/user_operation/controllers.ts
  packages/backend/src/modules/models/template.ts
  packages/backend/src/modules/models/user_operation.ts
  packages/backend/src/utils/pagination.ts
Labels: enhancement

#63 issue #62 resolved
  packages/backend/src/api/larch/template/controllers.ts
  packages/backend/src/api/larch/template/routes.ts
Labels: feature

#64 apply fixes to network api's
  packages/backend/migrations/0.initial.js
  packages/backend/src/api/larch/network/controllers.ts
  packages/backend/src/api/larch/network/routes.ts
  packages/backend/src/api/larch/network/schemas.ts
  packages/backend/src/api/larch/network/validations.ts
  packages/backend/src/api/larch/template/schemas.ts
  packages/backend/src/modules/models/exec_run.ts
  packages/backend/src/modules/models/network.ts
  packages/backend/src/modules/network.ts
  packages/backend/src/modules/zombienet.ts
  packages/backend/src/utils/declaration.ts
  packages/backend/src/utils/fs_helper.ts
Labels: bug, enhancement

#67 dead code elimiation
  packages/backend/src/utils/index.ts
  packages/backend/src/utils/testZombienetRunner.ts
  packages/backend/src/utils/zombienetRunner.ts
Labels: bug, enhancement

#69 network cleanup
  packages/backend/src/api/larch/network/controllers.ts
  packages/backend/src/modules/exec_run.ts
  packages/backend/src/modules/models/exec_run.ts
  packages/backend/src/modules/models/network.ts
  packages/backend/src/modules/network.ts
  packages/backend/src/modules/providers/common.ts
  packages/backend/src/modules/providers/podman.ts
  packages/backend/src/modules/zombienet.ts
Labels: enhancement

#70 Cleanup fixes
  packages/backend/src/config.ts
  packages/backend/src/modules/exec_run.ts
  packages/backend/src/modules/network.ts
  packages/backend/src/modules/providers/common.ts
  packages/backend/src/modules/providers/podman.ts
  packages/backend/src/utils/fs_helper.ts
Labels: enhancement

#71 Added dsl_edit page and create_network pages
  package-lock.json
  packages/ui/package.json
  packages/ui/src/App.tsx
  packages/ui/src/components/header.tsx
  packages/ui/src/components/main_menu.tsx
  packages/ui/src/index.css
  packages/ui/src/pages/dashboard/components/dashboard_content.tsx
  packages/ui/src/pages/dsl_edit/assets/Search.svg
  packages/ui/src/pages/dsl_edit/assets/dlt.svg
  packages/ui/src/pages/dsl_edit/assets/duplicate.svg
  packages/ui/src/pages/dsl_edit/components/Main.tsx
  packages/ui/src/pages/network/assets/upload.svg
  packages/ui/src/pages/network/components/create_network/assets/Search.svg
  packages/ui/src/pages/network/components/create_network/assets/dlt.svg
  packages/ui/src/pages/network/components/create_network/assets/down.svg
  packages/ui/src/pages/network/components/create_network/assets/duplicate.svg
  packages/ui/src/pages/network/components/create_network/assets/up.svg
  packages/ui/src/pages/network/components/create_network/assets/upload.svg
  packages/ui/src/pages/network/components/create_network/collator.tsx
  packages/ui/src/pages/network/components/create_network/create_network.tsx
  packages/ui/src/pages/network/components/create_network/hrmp.tsx
  packages/ui/src/pages/network/components/create_network/linecount.tsx
  packages/ui/src/pages/network/components/create_network/navbar.tsx
  packages/ui/src/pages/network/components/create_network/parachain.tsx
  packages/ui/src/pages/network/components/create_network/relaychain.tsx
  packages/ui/src/pages/network/components/create_network/theme.tsx
  packages/ui/src/pages/network/components/network_content.tsx
  packages/ui/src/pages/setting/assets/Search.svg
  packages/ui/src/pages/setting/components/Main.tsx
  packages/ui/src/pages/template/components/config.tsx
  packages/ui/tailwind.config.cjs
Labels: enhancement

#73 improve ui route and errors
  packages/backend/src/index.ts
  packages/backend/src/modules/models/exec_run.ts
  packages/backend/src/modules/network.ts
  packages/backend/src/server.ts
Labels: bug, enhancement

#75 update package-lock.json
  package-lock.json
Labels: bug

#78 fix dashboard page
  packages/ui/src/App.tsx
  packages/ui/src/components/layout/Mainlayout.tsx
  packages/ui/src/components/main_menu.tsx
  packages/ui/src/index.css
  packages/ui/src/pages/dashboard/assets/Activity.svg
  packages/ui/src/pages/dashboard/assets/Dashboard.svg
  packages/ui/src/pages/dashboard/assets/Documentation.svg
  packages/ui/src/pages/dashboard/assets/Email.svg
  packages/ui/src/pages/dashboard/assets/Help.svg
  packages/ui/src/pages/dashboard/assets/My-Network.svg
  packages/ui/src/pages/dashboard/assets/Setting.svg
  packages/ui/src/pages/dashboard/assets/User-Editor.svg
  packages/ui/src/pages/dashboard/assets/image.svg
  packages/ui/src/pages/dashboard/assets/logo.svg
  packages/ui/src/pages/dashboard/assets/notification.svg
  packages/ui/src/pages/dashboard/assets/plus.svg
  packages/ui/src/pages/dashboard/assets/react.svg
  packages/ui/src/pages/dashboard/assets/template.svg
  packages/ui/src/pages/dashboard/components/card.tsx
  packages/ui/src/pages/dashboard/components/dashboard_content.tsx
  packages/ui/src/pages/dashboard/components/page.tsx
  packages/ui/src/pages/dashboard/page.tsx
  packages/ui/src/pages/network/components/create_network/navbar.tsx
Labels: bug

#79 fix activity page
  .vscode/settings.json
  package-lock.json
  packages/ui/.eslintignore
  packages/ui/.eslintrc.cjs
  packages/ui/package.json
  packages/ui/src/App.tsx
  packages/ui/src/components/assets/Search.svg
  packages/ui/src/components/assets/arrowleft.svg
  packages/ui/src/components/assets/arrowright.svg
  packages/ui/src/components/pagination.tsx
  packages/ui/src/pages/activity/components/Main.tsx
  packages/ui/src/pages/activity/components/Parent.tsx
  packages/ui/src/pages/activity/components/listing.tsx
  packages/ui/src/pages/activity/components/table.tsx
  packages/ui/src/pages/activity/page.tsx
  packages/ui/src/utils/apiCollection/fetchApi.ts
  packages/ui/src/utils/time.ts
Labels: enhancement

#80 move create network button to template page
  packages/ui/src/components/pagination.tsx
  packages/ui/src/pages/network/components/network_content.tsx
  packages/ui/src/pages/template/components/config.tsx
Labels: enhancement

#82 fix promise controllers throwing errors
  packages/backend/src/api/larch/network/routes.ts
  packages/backend/src/api/larch/template/routes.ts
  packages/backend/src/api/larch/user_operation/routes.ts
  packages/backend/src/api/larch/version/controllers.ts
  packages/backend/src/server.ts
  packages/backend/src/utils/misc.ts
  packages/ui/src/pages/activity/components/table.tsx
  packages/ui/src/pages/network/components/Parent.tsx
  packages/ui/src/pages/network/components/network_content.tsx
  packages/ui/src/pages/network/components/table.tsx
  packages/ui/src/pages/template/components/table.tsx
Labels: bug, enhancement

#85 update setting UI
  packages/ui/.eslintignore
  packages/ui/.eslintrc.cjs
  packages/ui/src/App.tsx
  packages/ui/src/index.css
  packages/ui/src/pages/setting/assets/Search.svg
  packages/ui/src/pages/setting/components/Main.tsx
  packages/ui/src/pages/setting/page.tsx
  packages/ui/src/utils/apiCollection/fetchApi.ts
  packages/ui/src/utils/setting.ts
  packages/ui/tailwind.config.cjs
Labels: enhancement

#86 set pagination style
  packages/ui/src/components/pagination.css
  packages/ui/src/components/pagination.tsx
  packages/ui/src/pages/template/components/config.tsx
Labels: enhancement

#88 add toast notification, build cache support
  nx.json
  package-lock.json
  package.json
  packages/backend/package.json
  packages/backend/src/api/larch/network/controllers.ts
  packages/backend/src/api/larch/template/controllers.ts
  packages/backend/src/modules/user_operation.ts
  packages/backend/src/server.ts
  packages/cli/package.json
  packages/ui/package.json
  packages/ui/src/components/layout/Mainlayout.tsx
  packages/ui/src/pages/activity/components/listing.tsx
  packages/ui/src/pages/network/components/Parent.tsx
  packages/ui/src/pages/setting/page.tsx
  packages/ui/src/pages/template/components/Parent.tsx
  packages/ui/src/utils/api.ts
  packages/ui/src/utils/notifications.ts
  packages/ui/tailwind.config.cjs
Labels: enhancement, feature

#92 Update page on element operations
  packages/ui/src/App.tsx
  packages/ui/src/components/header.tsx
  packages/ui/src/components/layout/Mainlayout.tsx
  packages/ui/src/components/main_menu.tsx
  packages/ui/src/index.css
  packages/ui/src/main.tsx
  packages/ui/src/pages/Network.tsx
  packages/ui/src/pages/activity/components/listing.tsx
  packages/ui/src/pages/button.tsx
  packages/ui/src/pages/network/components/listing.tsx
  packages/ui/src/pages/network/components/network_content.tsx
  packages/ui/src/pages/network/page.tsx
  packages/ui/src/pages/store.tsx
  packages/ui/src/pages/template/components/config.tsx
  packages/ui/src/pages/template/components/listing.tsx
  packages/ui/src/pages/template/components/table.tsx
  packages/ui/src/pages/template/page.tsx
  readme.md
Labels: bug, enhancement

#97 fix network create and delete
  .vscode/settings.json
  packages/backend/src/api/larch/network/schemas.ts
  packages/backend/src/api/larch/template/schemas.ts
  packages/backend/src/modules/models/network.ts
  packages/backend/src/modules/network.ts
  packages/ui/src/App.tsx
  packages/ui/src/pages/network/components/create_network/create_network.tsx
  packages/ui/src/pages/network/components/create_network/hrmp.tsx
  packages/ui/src/pages/network/components/create_network/parachain.tsx
  packages/ui/src/pages/network/components/create_network/relaychain.tsx
  packages/ui/src/pages/network/components/create_network/theme.tsx
  packages/ui/src/pages/network/components/listing.tsx
  packages/ui/src/pages/network/components/table.tsx
  packages/ui/src/pages/template/components/listing.tsx
  packages/ui/src/pages/template/components/modal.tsx
  packages/ui/src/utils/api.ts
Labels: bug, enhancement

#98 Adding filter
  packages/backend/src/modules/models/user_operation.ts
  packages/ui/src/components/main_menu.tsx
  packages/ui/src/components/pagination.css
  packages/ui/src/components/pagination.tsx
  packages/ui/src/index.css
  packages/ui/src/pages/activity/components/filter.tsx
  packages/ui/src/pages/activity/components/listing.tsx
  packages/ui/src/pages/activity/components/table.tsx
  packages/ui/src/pages/activity/page.tsx
  packages/ui/src/pages/dsl_edit/components/Main.tsx
  packages/ui/src/pages/template/components/table.tsx
  packages/ui/src/store/activityStore.ts
  packages/ui/tailwind.config.cjs
Labels: enhancement

#99 Network list filter
  packages/ui/src/components/filter.tsx
  packages/ui/src/pages/activity/components/listing.tsx
  packages/ui/src/pages/network/components/listing.tsx
  packages/ui/src/pages/network/components/table.tsx
  packages/ui/src/pages/template/components/listing.tsx
  packages/ui/src/pages/template/components/table.tsx
  packages/ui/src/store/activityStore.ts
  packages/ui/src/store/commonStore.ts
  packages/ui/src/store/networkStore.ts
  packages/ui/src/store/templateStore.ts
Labels: enhancement

#104 add command and logs support
  package-lock.json
  packages/backend/src/modules/exec_run.ts
  packages/backend/src/modules/network.ts
  packages/ui/package.json
  packages/ui/src/pages/dashboard/page.tsx
  packages/ui/src/pages/network/components/listing.tsx
  packages/ui/src/pages/network/components/table.tsx
  packages/ui/src/pages/run-list/components/commandModal.tsx
  packages/ui/src/pages/run-list/components/listing.tsx
  packages/ui/src/pages/run-list/components/standardOutputModal.tsx
  packages/ui/src/pages/run-list/components/table.tsx
  packages/ui/src/utils/api.ts
  packages/ui/src/utils/encoding.ts
Labels: enhancement, feature

#105 Create nw page dynamic with api integration
  packages/ui/src/App.tsx
  packages/ui/src/pages/create_network/components/assets/Search.svg
  packages/ui/src/pages/create_network/components/assets/dlt.svg
  packages/ui/src/pages/create_network/components/assets/down.svg
  packages/ui/src/pages/create_network/components/assets/duplicate.svg
  packages/ui/src/pages/create_network/components/assets/up.svg
  packages/ui/src/pages/create_network/components/assets/upload.svg
  packages/ui/src/pages/create_network/components/hrmp.tsx
  packages/ui/src/pages/create_network/components/linecount.tsx
  packages/ui/src/pages/create_network/components/modal.tsx
  packages/ui/src/pages/create_network/components/navbar.tsx
  packages/ui/src/pages/create_network/components/parachain.tsx
  packages/ui/src/pages/create_network/components/relaychain.tsx
  packages/ui/src/pages/create_network/components/testConfig.tsx
  packages/ui/src/pages/create_network/components/theme.tsx
  packages/ui/src/pages/create_network/create_network.tsx
  packages/ui/src/pages/network/components/create_network/collator.tsx
  packages/ui/src/pages/network/components/create_network/create_network.tsx
  packages/ui/src/pages/network/components/create_network/hrmp.tsx
  packages/ui/src/pages/network/components/create_network/parachain.tsx
  packages/ui/src/pages/network/components/create_network/relaychain.tsx
  packages/ui/src/pages/network/page.tsx
  packages/ui/src/pages/template/page.tsx
  packages/ui/src/store/createNetworkStore.ts
  packages/ui/src/utils/api.ts
Labels: enhancement

#106 add delete and test button functionality and add documentation page
  packages/ui/src/App.tsx
  packages/ui/src/components/main_menu.tsx
  packages/ui/src/pages/documentation/page.tsx
  packages/ui/src/pages/network/components/listing.tsx
  packages/ui/src/pages/network/components/modaldelete.tsx
  packages/ui/src/pages/network/components/modaltest.tsx
  packages/ui/src/pages/network/components/table.tsx
Labels: enhancement

#107 fix network listing
  packages/ui/src/pages/network/components/listing.tsx
Labels: bug

#109 add version fix for binary build
  .gitignore
  docs/development/binary_build.md
  packages/backend/.eslintignore
  packages/backend/.eslintrc.cjs
  packages/backend/package.json
  packages/backend/scripts/version.mjs
  packages/backend/src/config.ts
  packages/backend/src/version.ts
  packages/backend/tsconfig.json
  packages/cli/.eslintrc.cjs
  packages/cli/dist/cli.js
  packages/cli/package.json
  packages/cli/scripts/version.mjs
  packages/cli/src/cli.ts
  packages/cli/src/version.ts
  packages/cli/tsconfig.json
  packages/ui/package.json
  readme.md
Labels: bug, enhancement

#110 make changes on documentation page and add purge functionality on act…
  packages/ui/src/pages/activity/components/listing.tsx
  packages/ui/src/pages/activity/page.tsx
  packages/ui/src/pages/documentation/page.tsx
  packages/ui/src/pages/template/page.tsx
  packages/ui/src/utils/api.ts
Labels: enhancement

#112 fix UI edit functionality
  packages/backend/src/api/larch/template/routes.ts
  packages/ui/src/pages/create_network/components/modal.tsx
  packages/ui/src/pages/create_network/components/testConfig.tsx
  packages/ui/src/pages/create_network/create_network.tsx
  packages/ui/src/pages/template/components/table.tsx
  packages/ui/src/pages/template/page.tsx
  packages/ui/src/store/createNetworkStore.ts
  packages/ui/src/utils/api.ts
Labels: bug

#113 editor reset and auto fill fixes
  packages/ui/src/pages/create_network/components/testConfig.tsx
  packages/ui/src/pages/create_network/create_network.tsx
Labels: bug

#114 fix network status update on network create
  packages/backend/src/modules/models/exec_run.ts
  packages/backend/src/modules/network.ts
  packages/backend/src/modules/providers/common.ts
  packages/backend/src/modules/providers/podman.ts
  packages/ui/src/pages/documentation/page.tsx
Labels: bug, enhancement

#115 HRMP changes done
  packages/ui/src/pages/create_network/components/hrmp.tsx
  packages/ui/src/pages/create_network/components/relaychain.tsx
  packages/ui/src/pages/create_network/components/testConfig.tsx
  packages/ui/src/pages/create_network/create_network.tsx
  packages/ui/src/store/createNetworkStore.ts
Labels: enhancement

#116 Improvements and fixes
  packages/ui/src/components/header.tsx
  packages/ui/src/pages/create_network/components/hrmp.tsx
  packages/ui/src/pages/create_network/components/modal.tsx
  packages/ui/src/pages/create_network/components/testConfig.tsx
  packages/ui/src/pages/create_network/create_network.tsx
  packages/ui/src/store/createNetworkStore.ts
Labels: bug

#119 Design imp
  packages/ui/src/components/loader.tsx
  packages/ui/src/components/refresh.tsx
  packages/ui/src/pages/activity/components/listing.tsx
  packages/ui/src/pages/dashboard/page.tsx
  packages/ui/src/pages/network/components/listing.tsx
  packages/ui/src/pages/run-list/components/listing.tsx
  packages/ui/src/pages/run-list/components/standardOutputModal.tsx
  packages/ui/src/pages/store.tsx
  packages/ui/src/pages/template/components/listing.tsx
Labels: bug

#120 Loader added on all pages
  packages/ui/src/components/loader.css
  packages/ui/src/components/loader.tsx
  packages/ui/src/pages/activity/components/listing.tsx
  packages/ui/src/pages/dashboard/page.tsx
  packages/ui/src/pages/network/components/listing.tsx
  packages/ui/src/pages/run-list/components/listing.tsx
  packages/ui/src/pages/template/components/listing.tsx
Labels: enhancement

#124 Filter store removed for network, template, runlist and activity page
  packages/ui/src/components/filter.tsx
  packages/ui/src/pages/activity/components/listing.tsx
  packages/ui/src/pages/network/components/listing.tsx
  packages/ui/src/pages/run-list/components/listing.tsx
  packages/ui/src/pages/template/components/listing.tsx
  packages/ui/src/store/activityStore.ts
  packages/ui/src/store/commonStore.ts
  packages/ui/src/store/networkStore.ts
  packages/ui/src/store/runStore.ts
  packages/ui/src/store/templateStore.ts
  packages/ui/src/types/filter.types.ts
Labels: enhancement

#127 Fix the create network template.
  package-lock.json
  packages/ui/package.json
  packages/ui/src/App.tsx
  packages/ui/src/assets/ArrowDown.svg
  packages/ui/src/assets/ArrowUp.svg
  packages/ui/src/assets/Trash.svg
  packages/ui/src/components/layout/HeaderLayout.tsx
  packages/ui/src/components/layout/Mainlayout.tsx
  packages/ui/src/components/layout/SidebarLayout.tsx
  packages/ui/src/pages/create_network/components/assets/Search.svg
  packages/ui/src/pages/create_network/components/assets/dlt.svg
  packages/ui/src/pages/create_network/components/assets/down.svg
  packages/ui/src/pages/create_network/components/assets/duplicate.svg
  packages/ui/src/pages/create_network/components/assets/up.svg
  packages/ui/src/pages/create_network/components/assets/upload.svg
  packages/ui/src/pages/create_network/components/hrmp.tsx
  packages/ui/src/pages/create_network/components/linecount.tsx
  packages/ui/src/pages/create_network/components/modal.tsx
  packages/ui/src/pages/create_network/components/navbar.tsx
  packages/ui/src/pages/create_network/components/parachain.tsx
  packages/ui/src/pages/create_network/components/relaychain.tsx
  packages/ui/src/pages/create_network/components/testConfig.tsx
  packages/ui/src/pages/create_network/create_network.tsx
  packages/ui/src/pages/create_template/components/Modal.tsx
  packages/ui/src/pages/create_template/components/Navbar.tsx
  packages/ui/src/pages/create_template/components/Theme.tsx
  packages/ui/src/pages/create_template/components/steps/Step01.tsx
  packages/ui/src/pages/create_template/components/steps/Step02.tsx
  packages/ui/src/pages/create_template/components/steps/Step03.tsx
  packages/ui/src/pages/create_template/components/steps/Step04.tsx
  packages/ui/src/pages/create_template/components/steps/Step05.tsx
  packages/ui/src/pages/create_template/index.tsx
  packages/ui/src/pages/documentation/page.tsx
  packages/ui/src/pages/network/components/table.tsx
  packages/ui/src/pages/run-list/components/listing.tsx
  packages/ui/src/pages/template/components/listing.tsx
  packages/ui/src/pages/template/components/table.tsx
  packages/ui/src/store/CreateTemplate.ts
  packages/ui/tailwind.config.cjs
Labels: enhancement
